Dk 146
prgrms-web-devcourse/Team_04_SFam_BE pull request #15
Opened 2022-07-26 19:18 UTC by pjh612

## ✅  작업 단위

- [[DK-146] setting : QueryDsl 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/182b274f570a14eb0a049b3218b5c862934f71e4)
  - querydsl 디펜던시와 설정을 추가했습니다.

- [[DK-146] feat : UserConverter 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/022bce9f0a2cad2578b631e349fee52cacfa9f3b)
  - user컨버터를 추가했습니다.

- [[DK-146] feat : existsTeamMember 함수 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/7bb90365da01f2b1342c3a347b902c881fb0325a)
  - 이미 팀멤버인지 판별하는 함수를 추가했습니다.
- [[DK-146] feat : 팀 초대 기능 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/464c27d72ed67579a2ac03facc14df736539dcfe)
  - 팀 초대 API 입니다. 팀 초대시 이미 초대된 사람이라면 PersistenceException을, 이미 팀원이거나 초대하는사람이 팀 리더가 아니면  BusinessException을 던집니다.

- [[DK-146] setting : querydsl 테스트 config 파일 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/de024b01e8f6b836f8364c42243b4da263db62c4)
  - 테스트 코드에서 쿼리 dsl 설정을 주입받기 위함입니다.

- [[DK-146] feat : 팀 조회 시 팀 멤버 리스트 반환하도록 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/e43f3617b5f5b2ae64a6325aafa982a888f2ed67)
- [[DK-146] test : TeamMemberGiverService 테스트 코드 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/362d8d99d962a7e38f30525f3156d20cb152cce3)
  - TeamMemberGiverService로 TeamResponse에 포함합니다.

- [feat : validation, swagger 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/834b32d0eb93ac6fdd4dbc0aa1f3cbb4189d7edd)
  - 스웨거, 유효성 검사 추가했습니다.
## 🤔 고민 했던 부분

- [test : 테스트 코드에 @WithMockJwtAuthentication 추가](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/fd6ee8592c03050cf53d2e65b872575227cc8e2b)
  - 테스트 코드가 돌아가지 않아 @WithMockJwtAuthentication 사용했습니다.

## 🔊 HELP !!

- TeamMemberResponse가 TeamMember entity의 대표격 DTO인데 저렇게 userid, nickname, role만 가져도 되는건지?
- 특히 GiverService 라는 것은 순환참조를 해결하기위해 다른 서비스를 의존하지 않고 다른 서비스가 필요로 하는 데이터를 반환해주는건데 대표격 DTO가 저런 한정적인 데이터를 반환해도되는건지?
  - TeamMemberResponse는 teamMemberId, userResponse, teamResponse, role 모든 데이터를 가져야되는건 아닌지?
- 특정 View에 대한 Response는 별도의 DTO를 만들어야되는 것은 아닌지?
  - ex) TeamMemberResponse 하위에 프로필에서 팀원 리스트 출력할때는 ProfileViewResponse(userID, nickname, role), 팀원 관리 페이지에서는 TeamManagementViewResponse(userid, nickname, 가입일, role, 매너 온도) 등 view마다 dto를 별도로 생성하는 방식
  - 물론 지금 당장은 필요없어보입니다. -> 규모가 커졌을때는?

2022-07-26 21:47 UTC, HYEBPARK approved these changes
제가 궁금한 부분에 대해서만 작성했습니당 ~! 진형님 수고하셨습니당 ~ 

- TeamMemberResponse는 default로 모든 필드를 다가져가는게 맞다고 생각합니다. 해당 상황에 맞춰진 dto가 아닌 말그대로 TeamMember를 대표하는 DTO 라고 생각하기 때문입니다. 
- 특정 View에 대한 Response는 default를 사용하는 상세조회격? 로직 이외에는 따로 만드는게 맞다고 생각합니다. 진형님이 말씀하신 것 처럼 페이지 단위로 나누는게 좋을 것 같습니다.

2022-07-26 21:47 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/common/exception/ErrorCode.java
> +	ALREADY_TEAM_MEMBER("M0001", "Already member of team" , HttpStatus.BAD_REQUEST);
별건아니지만 나중에 NOT_FOUND 를 001로 가져가는건 어떨까용 ?

2022-07-26 21:47 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/teaminvitation/controller/TeamInvitationController.java
> +		if (auth == null)
해당부분은 앞으로 매번 체크를 해줘야하는 부분인가요 !?

2022-07-26 21:47 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		TeamResponse teamResponse = teamService.findById(request.teamId());
이와 같은 부분도 나중에 Giver로 다 변경하는건가용?

2022-07-26 21:47 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/teammember/service/TeamMemberService.java
>  	@Transactional
최상단에 `readOnly = true` 를 빼셨는데 여기 `@Transactional` 을 사용하시는 이유가 있으신가요? 
그리고 바로 위에 `TeamMemberGiverService` 에서 `@Transactional`을 최상단으로 가져가시는 이유가 궁금합니다!

2022-07-27 02:51 UTC, HyoungUkJJang requested changes
새벽까지 고생 많으셨습니다 진형님..! 소소한 의견을 남겨봤습니다 :)

2022-07-27 02:51 UTC, HyoungUkJJang commented on src/main/java/com/kdt/team04/domain/teaminvitation/entity/TeamInvitation.java
> +
세 줄이 띄워져 있는 것 같습니당

2022-07-27 02:51 UTC, HyoungUkJJang commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +	private final TeamService teamService;
순환 참조는 오늘 이야기 해보고 끊어낼 생각이신가용?

2022-07-27 02:51 UTC, HyoungUkJJang commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		return new TeamInvitationResponse.InviteResponse(teamInvitationRepository.save(invitation).getId());
save 메서드를 분리해주시는건 어떠신가용?

```java
TeamInvitation invitation = teamInvitationRepository.save(invitation);
return new TeamInvitationResponse.InviteResponse(invitation.getId());
```

2022-07-27 02:51 UTC, HyoungUkJJang commented on src/main/java/com/kdt/team04/domain/teammember/repository/CustomizedTeamMemberRepositoryImpl.java
> +	public boolean existsByTeamIdAndMemberId(Long teamId, Long userId) {
음 제가 아직 잘 몰라서..ㅠㅠ 이미 팀에 존재하는 맴버인지 아닌지를 검증하는 메서드로 보이는데 그렇다면 DataJPA의 existsByTeamIdAndUserId랑 어떤 차이가 있는지 궁금합니다..!

2022-07-27 03:26 UTC, whyWhale commented
커밋 단위가 지금 파일 기준인데 기능 위주로 커밋을 남기지 않는 이유가 무엇인가요?

2022-07-27 03:33 UTC, pjh612 commented on src/main/java/com/kdt/team04/common/exception/ErrorCode.java
> +	ALREADY_TEAM_MEMBER("M0001", "Already member of team" , HttpStatus.BAD_REQUEST);
좋아요~

2022-07-27 03:34 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/controller/TeamInvitationController.java
> +		if (auth == null)
2차 검증이라고 볼 수 있을 것 같아요 인스타뀨램에서도 글케 했었는데 아닌가용

2022-07-27 03:34 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		TeamResponse teamResponse = teamService.findById(request.teamId());
일단은 순환참조가 일어나면 그때 바꾸는걸로 생각하고 있었습니당

2022-07-27 03:35 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teammember/service/TeamMemberService.java
>  	@Transactional
네.. 단순히 실수에용 나중에 바꿔야지하고 급하게 치다가 고치는거 깜빡했슴다 수정하겠습니다~

2022-07-27 03:36 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/entity/TeamInvitation.java
> +
수정하겠습니다~

2022-07-27 03:37 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +	private final TeamService teamService;
당장은 순환참조가 안일어나기도 했고 솔직히 어디를 손대야될지도 막막해서 그냥 일단은 올렸슴다

2022-07-27 03:37 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		return new TeamInvitationResponse.InviteResponse(teamInvitationRepository.save(invitation).getId());
좋아요

2022-07-27 03:39 UTC, whyWhale reviewed
고생 하셧습둥 :)

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/teaminvitation/entity/TeamInvitation.java
> +	public TeamInvitation(Long id, Team team, User target, InvitationStatus status) {
개인적으로 파리미터가 4가지 이상이면 builder를 사용하고 있는데 builder를 사용하시는것은 어떠신가요?

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/common/exception/ErrorCode.java
>  	TOKEN_NOT_FOUND("A0001", "Not found token", HttpStatus.NOT_FOUND),
에러코드 가이드를 노션에 지속적으로 문서로 관리하면 좋을 것 같습니다. 어떡해 생각하시나요?

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/teaminvitation/controller/TeamInvitationController.java
> +		if (auth == null)
ah ma doo yo

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		}
if 분기문 다음에 띄어쓰기를 쓰시면 어떨가용

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		if (!Objects.equals(team.getLeader().getId(), myId)) {
기본적으로 Long type에 equals를 사용할 수 있는데 Objects를 사용하신 이유가 있으신가요?

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/teammember/repository/CustomizedTeamMemberRepositoryImpl.java
> +	public boolean existsByTeamIdAndMemberId(Long teamId, Long userId) {
jo doo yoooooong

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/teammember/service/TeamMemberGiverService.java
> +@Transactional
밑에 메소드가 read 하나인데 readonly 안쓰신거는 어떤 이유로 하신건가요?

2022-07-27 03:39 UTC, whyWhale commented on src/main/java/com/kdt/team04/domain/user/UserConverter.java
> +		return new User(userResponse.id(), userResponse.password(), userResponse.username(), userResponse.nickname());
User entity에 4개 이상의 파라미터 변수명을 갖고 있는데 builder를 안사용하시는 이유가 있을까요?

2022-07-27 03:39 UTC, whyWhale approved these changes

2022-07-27 03:42 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/teaminvitation/controller/TeamInvitationController.java
> +		if (auth == null)
post 쪽에서는 진행을 안 했어가지구 😅 그렇게 하도록 하겠습니당 ~ !

2022-07-27 03:46 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/common/exception/ErrorCode.java
> +	ALREADY_TEAM_MEMBER("M0001", "Already member of team" , HttpStatus.BAD_REQUEST);
제가 나중에 수정하겠습니다 !

2022-07-27 03:53 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teammember/repository/CustomizedTeamMemberRepositoryImpl.java
> +	public boolean existsByTeamIdAndMemberId(Long teamId, Long userId) {
불필요했네요 지우겠슴다

2022-07-27 03:56 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		if (!Objects.equals(team.getLeader().getId(), myId)) {
Objectsr가 null safe한 장점이있는 것 같습니다? 내부 코드를 보니

2022-07-27 03:57 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teammember/service/TeamMemberGiverService.java
> +@Transactional
mistake~

2022-07-27 03:57 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/user/UserConverter.java
> +		return new User(userResponse.id(), userResponse.password(), userResponse.username(), userResponse.nickname());
이유는 없었슴다 별로 안필요해보였어요

2022-07-27 03:58 UTC, pjh612 commented on src/main/java/com/kdt/team04/common/exception/ErrorCode.java
>  	TOKEN_NOT_FOUND("A0001", "Not found token", HttpStatus.NOT_FOUND),
넵 좋아요

2022-07-27 03:58 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/entity/TeamInvitation.java
> +	public TeamInvitation(Long id, Team team, User target, InvitationStatus status) {
사용하겠습니다~

2022-07-27 03:58 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/teaminvitation/service/TeamInvitationService.java
> +		}
좋아요~

2022-07-27 06:19 UTC, midasWorld approved these changes
굳.. 고생하셨습니다!

2022-07-27 07:09 UTC, HyoungUkJJang approved these changes
고생하셨습니다 ! !

2022-07-27 07:10 UTC, merged