[Dk-82] 대결 신청 기능 구현
prgrms-web-devcourse/Team_04_SFam_BE pull request #30
Opened 2022-07-29 12:50 UTC by HYEBPARK

## ✅  작업 단위

- 대결 신청 기능 구현
- 대결 신청 기능 테스트 코드 작성

## 🤔 고민 했던 부분
- 네이밍 추천 언제나 환🌟영 입니다.  

## 🔊 HELP !!

2022-07-29 13:04 UTC, midasWorld approved these changes
고생하셨습니다!!! 👍

2022-07-29 13:04 UTC, midasWorld commented on src/main/java/com/kdt/team04/domain/matches/request/controller/RequestController.java
> +public class RequestController {
클래스명을 MatchProposalController나 ProposalController 로 하는건 어떨까요?

2022-07-29 13:04 UTC, midasWorld commented on src/main/java/com/kdt/team04/domain/matches/request/controller/RequestController.java
> +	public void propose(@PathVariable Long matchId, @AuthenticationPrincipal JwtAuthentication auth,
JwtAuthentication == null 인 경우의 체크가 필요하지 않을까요?

2022-07-29 13:04 UTC, midasWorld commented on src/main/java/com/kdt/team04/domain/matches/request/dto/MatchProposalRequest.java
> +		Long teamId,
팀 아이디도 not null 유효성 검사되도록 추가하는건 어떨까요?

2022-07-29 13:12 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/matches/request/controller/RequestController.java
> +	public void propose(@PathVariable Long matchId, @AuthenticationPrincipal JwtAuthentication auth,
뒤늦게 깨닫고 했심다 ... 🥲

2022-07-29 13:12 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/matches/request/dto/MatchProposalRequest.java
> +		Long teamId,
개인전 때문에 notNull 속성을 줄 수 없슴다 !

2022-07-29 13:13 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/matches/request/controller/RequestController.java
> +public class RequestController {
추가적인 리뷰를 받고 같이 수정하겠슴다 !

2022-07-29 13:34 UTC, HyoungUkJJang approved these changes
고생하셨습니다 혜빈님 ~!

2022-07-29 15:43 UTC, pjh612 requested changes
몇 가지 리뷰 드렸습니다 고생하셨습니다~

2022-07-29 15:43 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/matches/request/controller/RequestController.java
> +public class RequestController {
이왕이면 패키지명도 바꾸는게 좋겠네요 그러면

2022-07-29 15:43 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/matches/request/service/MatchProposalService.java
> +			teamProposalCreate(author, proposer, matchResponse, request.teamId(), request.content()) :
MathType이 팀 매치인데 teamId가 null일 때는 어떤 상황이 벌어지는지 확인해보셨나요? 육안으로 보기에는 NPE가 발생할 것 같은데 맞나요?

맞다면 검증 로직이 필요할 것 같습니다. Controller단에서 @AssertTrue를 사용할 수도 있을 것이고, 서비스 레이어에서 자체적으로 검증 로직을 추가할 수 있을 것 같아요~

2022-07-29 15:43 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/matches/request/service/MatchProposalService.java
> +	public Long create(Long proposerId, Long matchId, MatchProposalRequest.ProposalCreate request) {
제안자는 영어로 proponent 라고 하네요

2022-07-29 15:45 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/matches/request/service/MatchProposalService.java
> +	public Long create(Long proposerId, Long matchId, MatchProposalRequest.ProposalCreate request) {
proposer에 신청자 라는 뜻이 있어서 비슷하게 작성했슴다

2022-07-29 15:46 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/matches/request/service/MatchProposalService.java
> +			teamProposalCreate(author, proposer, matchResponse, request.teamId(), request.content()) :
생각 해보지 못했네요 create 할 때에도 이 부분을 생각해봐야겠슴다 👍🏻

2022-07-29 15:49 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/matches/request/service/MatchProposalService.java
> +	public Long create(Long proposerId, Long matchId, MatchProposalRequest.ProposalCreate request) {
글쿤여 그럼 이건 패스하고 팀매치 NPE 발생하는지 확인하시고 발생하면 수정해주세요! 완료되면 바로 approve하겠습니다~!~

2022-07-29 18:51 UTC, pjh612 commented
팀원이 2명인데 6:6경기에 신청할 수가 있을까요?

2022-07-29 20:23 UTC, HYEBPARK commented
팀원을 제한적으로 선택하지 않기로 정책 변경해서
대결 이후 팀원을 추가한다거나 음 신청자의 재량이 아닐까 생각했습니당 
이부분도 얘기 나누면 좋겠네욤

2022-07-30 02:26 UTC, pjh612 approved these changes

2022-07-30 03:25 UTC, merged