[DK-282] feat: 채팅 조회 API 구현
prgrms-web-devcourse/Team_04_SFam_BE pull request #44
Opened 2022-08-01 14:44 UTC by midasWorld

## ✅  작업 단위

### [[DK-282] feat: 채팅 조회 API 구현](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/29490526d23a95c00847945894e02fcd84fabc16)
- 신청자 혹은 작성자가 채팅 기록들 조회하는 기능 구현

### [[DK-282] test: 채팅 조회 API 테스트 코드 작성](https://github.com/prgrms-web-devcourse/Team_04_SFam_BE/commit/b817ab6969b4c85c52f9e22704dff1d4cc9edb7f)
- 신청 Giver, 채팅 서비스 테스트 코드 작성

2022-08-01 23:41 UTC, HYEBPARK approved these changes
동운님 수고하셨습니당 !!

2022-08-01 23:44 UTC, HYEBPARK commented on src/main/java/com/kdt/team04/domain/matches/proposal/repository/MatchProposalRepository.java
> +	Optional<MatchProposal> findMatchProposalById(@Param("id") Long id);
이 부분 네이밍 조금 헷갈렸는데 저만 그런거면 넘어가고 ... 
다른 분도 그러시면 이부분도 같이 생각해보면 좋을 것 같습니당 !

2022-08-02 05:58 UTC, pjh612 requested changes
몇가지 의견 드렸습니다!

2022-08-02 05:58 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/matches/proposal/dto/MatchChatResponse.java
> +		MatchProposalResponse.ChatMatch match,
MatchChattings 또는 Chattings
Chatting 등 명사형이 좋을 것 같아요

2022-08-02 05:58 UTC, pjh612 commented on src/main/java/com/kdt/team04/domain/matches/proposal/service/MatchProposalGiverService.java
> +		if (!Objects.equals(matchProposal.getUser().getId(), userId)
이렇게 복합적인 조건문이 들어갈 때에는 조건문을 함수로 빼서 어떤 조건인지 함수명으로써 표현하면 더욱 좋은 코드가 될 것 같습니다.

2022-08-02 06:22 UTC, midasWorld commented on src/main/java/com/kdt/team04/domain/matches/proposal/repository/MatchProposalRepository.java
> +	Optional<MatchProposal> findMatchProposalById(@Param("id") Long id);
`findProposalWithUserById` 로 변경하겠습니다!

2022-08-02 06:22 UTC, midasWorld commented on src/main/java/com/kdt/team04/domain/matches/proposal/dto/MatchChatResponse.java
> +		MatchProposalResponse.ChatMatch match,
`Chattings` 로 변경하겠슴둥

2022-08-02 06:32 UTC, midasWorld commented on src/main/java/com/kdt/team04/domain/matches/proposal/service/MatchProposalGiverService.java
> +		if (!Objects.equals(matchProposal.getUser().getId(), userId)
굳.. 수정하겠습니다! 👍

2022-08-02 07:55 UTC, pjh612 approved these changes
고생하셨습니다..!

2022-08-02 08:59 UTC, merged