[IK-393] 사용자가 팀 프로필을 확인할 수 있다. (리팩터링)
prgrms-web-devcourse/Team_04_SFam_BE pull request #68
Opened 2022-08-09 16:33 UTC by whyWhale

## ✅  작업 단위

⚠️  @HYEBPARK 은 반드시 봐주세요 !
- 테스트 코드에서 전역 변수로 선언되어 있는 것을 모두 지역으로 변경하였습니다.
- 테스트 코드에서 공통적으로 사용된 임시 객체 값들을 셋팅 할 수 있도록 함수화 했습니다.
- controllerMock Test를 추가 했습니다.

## 🤔 고민 했던 부분

- validation Test 를 넣을려던 찰나에 validation Test는  따로 가져갈지 같인 가져갈지 의논해보면 좋을 것 같습니 🥕 !
  - controller test 안에 모아둘지
  - 따로 class로 뺄지 

## 🔊 HELP !!
-

2022-08-09 16:50 UTC, pjh612 requested changes
고생하셨습니다 병연님 몇가지 수정해야될게 보이네요!

2022-08-09 16:50 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +	private final String END_POINT_PREFIX = "/api/teams";
BASE_END_POINT 라는 네이밍은 어떠세요

2022-08-09 16:50 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +				new ApiResponse<>(response))
개인적으로는 예상되는 요청과 응답을 given쪽에 별도로 request, response라는 변수로 빼두는게 테스트 코드 흐름 이해에 도움을 준다고 생각을 합니다.

2022-08-09 16:50 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/service/TeamServiceTest.java
>  	private MatchReviewGiverService matchReviewGiver;
PR과는 무관하지만 접근제어자 없애면 좋을 것 같습니다

2022-08-09 16:50 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +	private TeamService teamService;
접근제한자 제거해주십셔!

2022-08-09 16:50 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/service/TeamServiceTest.java
> +			.leader(null)
매개변수 user가 사용되지 않아보이는데 leader에 넣으려고하신건가요?

2022-08-09 16:50 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/service/TeamServiceTest.java
> +		Team newTeam = getDemoTeam(null);
리더 설정이 필요한듯해 보입니다.
리더 설정이 되지 않았음에도 불구하고 save에 성공한것 처럼 보이네요

2022-08-09 17:18 UTC, HyoungUkJJang approved these changes
고생하셨습니다 병연님 :)

2022-08-09 17:18 UTC, HyoungUkJJang commented on src/main/java/com/kdt/team04/domain/teams/teammember/service/TeamMemberGiverService.java
> +		return teamMemberRepository.findAllByTeamId(teamId).stream()
요거는 아마 혜빈님이 의도적으로 한번 필드로 빼시구 작업하신 것 같아 보입니다. 
한번에 처리하면 디버깅이 쉽지 않다는 의견을 본 것 같아요 👀

2022-08-09 17:18 UTC, HyoungUkJJang commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +		//given
여기 컨벤션 맞춰주시면 좋을 것 같습니다.

2022-08-09 20:00 UTC, pjh612 requested changes
수정되어야 될 것이 조금 보이는 것 같습니다 고생하셨습니다!!!!

2022-08-09 20:00 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +			String graterThan100Letter = Stream.generate(() -> "우")
해당 코드는 이 테스트 케이스에서는 불필요한 전제조건인것 같습니다!!

2022-08-09 20:00 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +		void faileToInvalidDescription() {
네이밍 오타가 보이네요

2022-08-09 20:00 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +			String graterThan100Letter = Stream.generate(() -> "우")
grater -> greater

2022-08-09 20:00 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +			String graterThan100Letter = Stream.generate(() -> "우")
또는 longer이 더 의미상 적합할 것 같습니다~

2022-08-09 20:00 UTC, pjh612 commented on src/test/java/com/kdt/team04/domain/teams/team/controller/TeamControllerTest.java
> +			List<String> invalids = List.of("", "    ", graterThan100Letter);
팀설명이 101자 이상인것에 대한 테스트라고 명시되어있지만 여러가지 경우에 대해서 테스트를 하고 있어요
하나의 테스트 함수에는 하나의 테스트 케이스가 들어가는게 적합하다고 생각합니다.

2022-08-09 21:35 UTC, midasWorld approved these changes
고생하셨습니다! 👍

2022-08-09 23:40 UTC, HYEBPARK commented on src/test/java/com/kdt/team04/domain/teams/team/model/entity/TeamValidationTest.java
> +	@Autowired TestEntityManager entityManager;
오우 개행 넣어줘야할 것 같아용

2022-08-09 23:44 UTC, HYEBPARK approved these changes
병연님 수고하셨습니당

2022-08-10 03:38 UTC, whyWhale commented
@pjh612 review 부탁드려욥 !
![스크린샷 2022-08-10 오후 12 38 06](https://user-images.githubusercontent.com/67587446/183807762-ee23e4a7-9690-4244-bd5b-e267664f2c79.png)

2022-08-10 05:26 UTC, pjh612 approved these changes
고생하셨습니다.

2022-08-10 12:13 UTC, merged